FROM golang:1.11.5-alpine

ENV PYTHONUSERBASE=/usr/local
ENV GOPATH=/var/opt
ENV PATH=$PATH:$GOPATH/bin

RUN mkdir -p /var/opt/src/sam-book-sample

RUN apk add --no-cache py-pip git make bash gcc libc-dev openssl curl && \
    apk add --no-cache python3 python3-dev && \
    pip3 install --upgrade pip && \
    pip3 install --user awscli==1.16.76 aws-sam-cli==0.9.0 && \
    go get -u github.com/golang/dep/cmd/dep && \
    go get -u golang.org/x/lint/golint

WORKDIR /var/opt/src/sam-book-sample
COPY . /var/opt/src/sam-book-sample

EXPOSE 3000
