FROM golang:1.11.5-alpine

RUN apk add --no-cache git make bash gcc libc-dev openssl curl && \
    go get -u github.com/golang/dep/cmd/dep && \
    go get -u golang.org/x/lint/golint && \
    go get -u github.com/kyoh86/richgo

WORKDIR /go/src/sam-book-sample
COPY . /go/src/sam-book-sample

RUN dep ensure


