[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.2.0"

[[constraint]]
  name = "github.com/guregu/dynamo"
  version = "1.1.0"

[[constraint]]
  name = "github.com/golang/glog"

[[constraint]]
  name = "gopkg.in/validator.v2"

[[constraint]]
  name = "golang.org/x/text"

[[constraint]]
  name = "github.com/memememomo/nomof"

[[constraint]]
  name = "github.com/memememomo/dbmock"
